name: Overlay

on:
  workflow_dispatch:
    inputs:
      FORK_URL:
        description: 'FORKED_URL'
        required: true
        default: 'https://github.com/Lesano/vendor_hardware_overlay_sea'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Prepare the environment
      run: |
        sudo apt -y install git-core git xmlstarlet 
        sudo apt-get install neofetch
        sudo apt update

    - name: Clone vendor_hardware_overlay_sea
      run: |
        PATH=~/bin:$PATH
        neofetch
        mkdir workspace
        cd workspace
        git clone ${{github.event.inputs.FORK_URL }}

    - name: Run test scripts
      run: |
        PATH=~/bin:$PATH
        cd workspace && cd vendor_hardware_overlay_sea
        git config --global user.name "Lesano"
        git config --global user.email "lesano@programmer.net"
        cd tests
        bash tests.sh

    - name: Build APK's
      run: |
        PATH=~/bin:$PATH
        cd workspace && cd vendor_hardware_overlay_sea && cd build
        bash build.sh

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        path: workspace/vendor_hardware_overlay_sea/build/*.apk
        name: Overlays
